<?php

namespace App\Livewire;

use App\Models\SaasPayment;
use App\Models\SaasInvoice;
use App\Models\Marquee;
use Livewire\Component;
use Illuminate\Support\Facades\DB;

class SaasPaymentForm extends Component
{
    public $invoice_id = '';
    public $amount = 0.00;
    public $payment_method = 'Bank Transfer';
    public $transaction_id = '';
    public $payment_date = '';
    public $notes = '';

    // Lists
    public $invoices = [];
    public $selectedInvoice = null;
    public $remainingBalance = 0.00;

    public function mount()
    {
        abort_unless(auth()->user()->isSuperAdmin(), 403);

        $this->payment_date = date('Y-m-d');
        
        // Fetch unpaid or partially paid invoices
        $this->invoices = SaasInvoice::with(['marquee', 'subscriptionPlan'])
            ->whereIn('payment_status', ['Unpaid', 'Partially Paid'])
            ->where('invoice_status', '!=', 'Cancelled')
            ->orderBy('created_at', 'desc')
            ->get();

        $queryInvoiceId = request()->query('invoice_id');
        if ($queryInvoiceId) {
            $this->invoice_id = $queryInvoiceId;
            $this->updatedInvoiceId($queryInvoiceId);
        }
    }

    public function updatedInvoiceId($value)
    {
        if (empty($value)) {
            $this->selectedInvoice = null;
            $this->amount = 0.00;
            $this->remainingBalance = 0.00;
            return;
        }

        $this->selectedInvoice = SaasInvoice::with(['payments', 'subscriptionPlan'])->find($value);
        if ($this->selectedInvoice) {
            $paidAmount = $this->selectedInvoice->payments->sum('amount');
            $this->remainingBalance = max(0, $this->selectedInvoice->total_amount - $paidAmount);
            $this->amount = $this->remainingBalance;
        }
    }

    protected function rules()
    {
        return [
            'invoice_id' => 'required|exists:saas_invoices,id',
            'amount' => 'required|numeric|min:0.01|max:' . ($this->remainingBalance ?: 99999999),
            'payment_method' => 'required|in:Cash,Bank Transfer,Easypaisa,JazzCash,Credit Card',
            'transaction_id' => 'nullable|string|max:100',
            'payment_date' => 'required|date',
            'notes' => 'nullable|string',
        ];
    }

    public function save()
    {
        abort_unless(auth()->user()->isSuperAdmin(), 403);

        $this->validate();

        DB::transaction(function() {
            $invoice = SaasInvoice::with(['payments', 'marquee', 'billingCycle'])->findOrFail($this->invoice_id);
            
            // Create payment
            SaasPayment::create([
                'payment_reference' => '', // Autogenerated in booted()
                'invoice_id' => $this->invoice_id,
                'marquee_id' => $invoice->marquee_id,
                'amount' => $this->amount,
                'payment_method' => $this->payment_method,
                'transaction_id' => $this->transaction_id,
                'payment_date' => $this->payment_date,
                'notes' => $this->notes,
            ]);

            // Re-calculate total payments including the newly created one
            $totalPaid = $invoice->payments()->sum('amount') + $this->amount;

            if ($totalPaid >= $invoice->total_amount) {
                // Update Invoice
                $invoice->update([
                    'payment_status' => 'Paid',
                    'invoice_status' => 'Paid',
                    'paid_date' => $this->payment_date,
                ]);

                // Automatically extend Marquee Tenant Owners Subscriptions
                $marquee = $invoice->marquee;
                $durationMonths = $invoice->billingCycle->duration_in_months;

                foreach ($marquee->owners as $owner) {
                    $currentEnd = $owner->subscription_ends_at;
                    $startDate = ($currentEnd && $currentEnd->isFuture()) ? $currentEnd : now();
                    $endDate = $startDate->copy()->addMonths($durationMonths);

                    $owner->update([
                        'subscription_plan_id' => $invoice->subscription_plan_id,
                        'subscription_ends_at' => $endDate,
                        'status' => 'active',
                    ]);
                }
            } else {
                $invoice->update([
                    'payment_status' => 'Partially Paid',
                ]);
            }
        });

        session()->flash('success', 'SaaS payment recorded successfully, subscription extended if fully paid.');
        return redirect()->route('saas-payments.index');
    }

    public function render()
    {
        return view('livewire.saas-payment-form');
    }
}
