<?php

namespace App\Livewire;

use App\Models\SaasPayment;
use App\Models\SaasInvoice;
use App\Models\Marquee;
use Livewire\Component;
use Illuminate\Support\Facades\DB;

class SaasPaymentForm extends Component
{
    public $invoice_id = '';
    public $discount = '';
    public $amount = 0.00;
    public $payment_method = 'Bank Transfer';
    public $transaction_id = '';
    public $payment_date = '';
    public $notes = '';

    // Lists
    public $invoices = [];
    public $selectedInvoice = null;
    public $remainingBalance = 0.00;

    public function mount()
    {
        abort_unless(auth()->user()->isSuperAdmin(), 403);

        $this->payment_date = date('Y-m-d');
        
        // Fetch unpaid or partially paid invoices
        $this->invoices = SaasInvoice::with(['user', 'subscriptionPlan'])
            ->whereIn('payment_status', ['Unpaid', 'Partially Paid'])
            ->where('invoice_status', '!=', 'Cancelled')
            ->orderBy('created_at', 'desc')
            ->get();

        $queryInvoiceId = request()->query('invoice_id');
        if ($queryInvoiceId) {
            $this->invoice_id = $queryInvoiceId;
            $this->updatedInvoiceId($queryInvoiceId);
        }
    }

    public function updatedInvoiceId($value)
    {
        if (empty($value)) {
            $this->selectedInvoice = null;
            $this->amount = 0.00;
            $this->remainingBalance = 0.00;
            $this->discount = '';
            return;
        }

        $this->selectedInvoice = SaasInvoice::with(['payments', 'subscriptionPlan'])->find($value);
        if ($this->selectedInvoice) {
            $paidAmount = $this->selectedInvoice->payments->sum('amount');
            $this->remainingBalance = max(0, $this->selectedInvoice->total_amount - $paidAmount);
            $this->amount = $this->remainingBalance;
            $this->discount = '';
        }
    }

    public function updatedDiscount($value)
    {
        if ($value === '' || $value === null) {
            $this->discount = '';
            $this->amount = $this->remainingBalance;
            return;
        }

        $discountVal = (float)$value;
        if ($discountVal > $this->remainingBalance) {
            $this->discount = $this->remainingBalance;
            $discountVal = $this->remainingBalance;
        }
        $this->amount = max(0, $this->remainingBalance - $discountVal);
    }

    protected function rules()
    {
        return [
            'invoice_id' => 'required|exists:saas_invoices,id',
            'discount' => 'nullable|numeric|min:0|max:' . $this->remainingBalance,
            'amount' => 'required|numeric|min:0|max:' . ($this->remainingBalance - ($this->discount ?: 0)),
            'payment_method' => 'required|in:Cash,Bank Transfer,Easypaisa,JazzCash,Credit Card',
            'transaction_id' => 'nullable|string|max:100',
            'payment_date' => 'required|date',
            'notes' => 'nullable|string',
        ];
    }

    public function save()
    {
        abort_unless(auth()->user()->isSuperAdmin(), 403);

        $this->validate();

        if (($this->amount ?: 0) + ($this->discount ?: 0) <= 0) {
            $this->addError('amount', 'The sum of payment amount and discount must be greater than 0.');
            return;
        }

        DB::transaction(function() {
            $invoice = SaasInvoice::with(['payments', 'user', 'billingCycle'])->findOrFail($this->invoice_id);
            
            $discountApplied = (float)($this->discount ?: 0);
            
            if ($discountApplied > 0) {
                // Update Invoice Discount and Total Amount
                $invoice->discount += $discountApplied;
                $invoice->total_amount -= $discountApplied;
                $invoice->save();

                // Re-post/update the Invoice Journal Voucher
                // 1. Delete the existing posted journal voucher for this invoice
                \App\Models\JournalVoucher::where('reference', $invoice->invoice_number)
                    ->whereNull('marquee_id')
                    ->delete();

                // 2. Re-create and post the updated journal voucher
                app(\App\Services\AccountingService::class)->postSaasInvoiceJournal($invoice);
            }

            // Create payment
            if ($this->amount > 0) {
                $payment = SaasPayment::create([
                    'payment_reference' => '', // Autogenerated in booted()
                    'invoice_id' => $this->invoice_id,
                    'user_id' => $invoice->user_id,
                    'amount' => $this->amount,
                    'payment_method' => $this->payment_method,
                    'transaction_id' => $this->transaction_id,
                    'payment_date' => $this->payment_date,
                    'notes' => $this->notes,
                ]);

                // Post double-entry journal entry to SaaS Ledger
                app(\App\Services\AccountingService::class)->postSaasPaymentJournal($payment);
            }

            // Re-calculate total payments including all saved ones
            $totalPaid = $invoice->payments()->sum('amount');

            if ($totalPaid >= $invoice->total_amount) {
                // Update Invoice
                $invoice->update([
                    'payment_status' => 'Paid',
                    'invoice_status' => 'Paid',
                    'paid_date' => $this->payment_date,
                ]);

                // Automatically extend the specific Business Owner User's Subscription
                $owner = $invoice->user;
                $durationMonths = $invoice->billingCycle->duration_in_months;

                if ($owner) {
                    $currentEnd = $owner->subscription_ends_at;
                    $startDate = ($currentEnd && $currentEnd->isFuture()) ? $currentEnd : now();
                    $endDate = $startDate->copy()->addMonths($durationMonths);

                    $owner->update([
                        'subscription_plan_id' => $invoice->subscription_plan_id,
                        'subscription_ends_at' => $endDate,
                        'status' => 'active',
                    ]);
                }
            } else {
                $invoice->update([
                    'payment_status' => 'Partially Paid',
                ]);
            }
        });

        session()->flash('success', 'SaaS payment recorded successfully, subscription extended if fully paid.');
        return redirect()->route('saas-payments.index');
    }

    public function render()
    {
        return view('livewire.saas-payment-form');
    }
}
