<?php

namespace App\Livewire;

use App\Models\SaasInvoice;
use App\Models\SaasPayment;
use App\Services\StripeBillingService;
use Livewire\Component;
use Illuminate\Support\Facades\DB;

class TenantBillingSuccess extends Component
{
    public $invoice = null;
    public $payment = null;
    public $error = null;

    public function mount(StripeBillingService $stripeService)
    {
        $sessionId = request()->query('session_id');
        $invoiceId = request()->query('invoice_id');

        if (!$sessionId || !$invoiceId) {
            $this->error = 'Invalid checkout session configuration parameters.';
            return;
        }

        $this->invoice = SaasInvoice::with(['subscriptionPlan', 'billingCycle', 'marquee'])->find($invoiceId);

        if (!$this->invoice) {
            $this->error = 'Requested subscription invoice record could not be found.';
            return;
        }

        // Retrieve and verify payment intent outcome from Stripe
        $result = $stripeService->retrieveCheckoutSession($sessionId);

        if (!$result['success'] || $result['payment_status'] !== 'paid') {
            $this->error = $result['message'] ?? 'Payment validation failed. Please contact support.';
            return;
        }

        DB::transaction(function() use ($result) {
            // Check if payment was already recorded
            $this->payment = SaasPayment::where('transaction_id', $result['transaction_id'])->first();

            if (!$this->payment) {
                // Record new SaaS payment
                $this->payment = SaasPayment::create([
                    'payment_reference' => '', // Autogenerated in booted()
                    'invoice_id' => $this->invoice->id,
                    'marquee_id' => $this->invoice->marquee_id,
                    'amount' => $this->invoice->total_amount,
                    'payment_method' => 'Credit Card',
                    'transaction_id' => $result['transaction_id'],
                    'payment_date' => now()->toDateString(),
                    'notes' => 'Stripe Online Checkout Session: ' . $result['transaction_id'],
                ]);

                // Update invoice to Paid
                $this->invoice->update([
                    'payment_status' => 'Paid',
                    'invoice_status' => 'Paid',
                    'paid_date' => now()->toDateString(),
                ]);

                // Extend Marquee tenant subscription ends date
                $marquee = $this->invoice->marquee;
                $durationMonths = $this->invoice->billingCycle->duration_in_months ?? 1;

                $currentEnd = $marquee->subscription_ends_at;
                $startDate = ($currentEnd && $currentEnd->isFuture()) ? $currentEnd : now();
                $endDate = $startDate->copy()->addMonths($durationMonths);

                $marquee->update([
                    'subscription_plan_id' => $this->invoice->subscription_plan_id,
                    'subscription_ends_at' => $endDate,
                    'status' => 'active',
                ]);
            }
        });
    }

    public function render()
    {
        return view('livewire.tenant-billing-success');
    }
}
